# Run the Guardener

name: Guarden my Dockerfile

# Manual run, provide group ID and desired tag at runtime
# Verify that the identity secret is added to the repository secrets before running
on:
  workflow_dispatch:
    secrets:
      GUARDENER_DEMO_CHAINCTL_IDENTITY:
        required: true
    inputs:
      NAMESPACE:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      GROUP:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: guardener-demo

jobs:
  # Run the Guardener to migrate the Dockerfile
  run-guardener:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repo
        uses: chainguard-actions/actions-checkout@23ad494bd955551cc56a72afafa44f978de21f4f # v4.3.1

      - name: Setup chainctl
        uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1

      - name: Get GitHub OIDC token
        id: oidc
        shell: bash
        run: |
          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Run guardener on Dockerfile
        shell: bash
        run: |
          chainctl auth login \
            --identity "${{ secrets.GUARDENER_DEMO_CHAINCTL_IDENTITY }}" \
            --identity-token "${{ steps.oidc.outputs.token }}"

          chainctl agent dockerfile build -f Dockerfile -t myapp:cg \
            --group "${{ inputs.GROUP }}" \
            --non-interactive

      - name: Save migrated Dockerfile
        uses: chainguard-actions/actions-upload-artifact@ae6fbddde3b6b879793bec6dd9a74a07077fe200 # v4.6.2
        with:
          name: Dockerfile.migrated
          path: ./Dockerfile.migrated
  
  # Build and push the migrated image to GitHub Container Registry
  build-and-push-image:
    needs: run-guardener
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out repo
        uses: chainguard-actions/actions-checkout@23ad494bd955551cc56a72afafa44f978de21f4f # v4.3.1

      - name: 'Login to GitHub Container Registry'
        uses: chainguard-actions/docker-login-action@93c9fb113ac946f14a332842652ec9600e25babc # v4.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Get GitHub OIDC token
        id: oidc
        shell: bash
        run: |
          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Setup chainctl
        uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
      
      - name: Auth with chainctl using OIDC token
        shell: bash
        run: |
          chainctl auth login \
            --identity "${{ secrets.GUARDENER_DEMO_CHAINCTL_IDENTITY }}" \
            --identity-token "${{ steps.oidc.outputs.token }}"

      - name: Download migrated Dockerfile
        uses: chainguard-actions/actions-download-artifact@ee0fd4035156db4b7f5f67e3a751b1e3ad3e216a # v4.3.0
        with:
          name: Dockerfile.migrated
          path: ./artifacts

      - name: Build and push image with new Dockerfile
        run: |
          docker build . -f ./artifacts/Dockerfile.migrated -t ghcr.io/${{ inputs.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
          docker push ghcr.io/${{ inputs.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}

      - name: Scan the image with Grype
        uses: chainguard-actions/anchore-scan-action@5470f64f241ff0b662c1efed80f982517e2340d6 # v7.4.0
        with:
          image: ghcr.io/${{ inputs.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
          fail-build: false
          output-format: json
          output-file: scan-results.json

      - name: Show Grype scan results
        run: |
          cat scan-results.json | jq '[.matches[] | {severity: .vulnerability.severity, id: .vulnerability.id, package: .artifact.name}]'